const DATA = window.RES_DATA;
const REGIONS = DATA.regions;
const MONTHS = ["Ene","Feb","Mar","Abr","May","Jun","Jul"];
const fmt = n => new Intl.NumberFormat("es-CL").format(Math.round(Number(n)||0));
const money = n => "$" + fmt(n);
const pct = (a,b) => b ? ((a-b)*100/b) : 0;
let selectedRegion = 13;
let regionSort = "volume";
function tooltipShow(e,html){const t=document.getElementById("tooltip");t.innerHTML=html;t.style.opacity=1;t.style.left=e.clientX+"px";t.style.top=e.clientY+"px";}
function tooltipHide(){document.getElementById("tooltip").style.opacity=0}
function buildRegionSelect(){const s=document.getElementById("regionSelect");s.innerHTML='<option value="all">Nacional</option>'+Object.entries(REGIONS).filter(([k])=>k!=="0").map(([k,v])=>`<option value="${k}" ${+k===13?'selected':''}>${v}</option>`).join("");s.onchange=()=>{const v=s.value;if(v==="all"){document.getElementById("regionContext").textContent="Vista nacional";renderAnomalies();renderClusters();}else{selectedRegion=+v;document.getElementById("regionContext").textContent=REGIONS[selectedRegion];renderTerritory();renderAnomalies();renderClusters();}};}
function svgBarChart(container,pairs){const el=document.getElementById(container),W=900,H=270,p={l:42,r:12,t:12,b:42},iw=W-p.l-p.r,ih=H-p.t-p.b,max=Math.max(...pairs.map(d=>d[1]))*1.08,bw=iw/pairs.length*.68,gap=iw/pairs.length;let svg=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">`;for(let i=0;i<4;i++){const y=p.t+ih*i/3;svg+=`<line class="gridline" x1="${p.l}" x2="${W-p.r}" y1="${y}" y2="${y}"/>`}pairs.forEach((d,i)=>{const h=ih*d[1]/max,x=p.l+i*gap+(gap-bw)/2,y=p.t+ih-h,partial=String(d[0])==="2026";svg+=`<rect x="${x}" y="${y}" width="${bw}" height="${h}" rx="4" fill="${partial?'#f28a3a':'#36536c'}" data-tip="${d[0]}|${fmt(d[1])}" class="hoverable"/>`;svg+=`<text class="axis-label" x="${x+bw/2}" y="${H-17}" text-anchor="middle">${d[0]}</text>`;});svg+=`</svg>`;el.innerHTML=svg;el.querySelectorAll(".hoverable").forEach(n=>{n.onmousemove=e=>tooltipShow(e,`<b>${n.dataset.tip.split("|")[0]}</b><br>${n.dataset.tip.split("|")[1]} constituciones`);n.onmouseleave=tooltipHide});}
function svgLineChart(container,labels,series,colors=["#f28a3a","#5a7891"]){const el=document.getElementById(container),W=800,H=250,p={l:40,r:15,t:18,b:38},iw=W-p.l-p.r,ih=H-p.t-p.b,vals=series.flatMap(s=>s.values),max=Math.max(...vals)*1.12,X=i=>p.l+(labels.length===1?0:iw*i/(labels.length-1)),Y=v=>p.t+ih-v/(max||1)*ih;let svg=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">`;for(let i=0;i<4;i++){const y=p.t+ih*i/3;svg+=`<line class="gridline" x1="${p.l}" x2="${W-p.r}" y1="${y}" y2="${y}"/>`}labels.forEach((l,i)=>svg+=`<text class="axis-label" x="${X(i)}" y="${H-13}" text-anchor="middle">${l}</text>`);series.forEach((s,si)=>{const pts=s.values.map((v,i)=>`${X(i)},${Y(v)}`).join(" ");svg+=`<polyline points="${pts}" fill="none" stroke="${colors[si]}" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>`;s.values.forEach((v,i)=>svg+=`<circle cx="${X(i)}" cy="${Y(v)}" r="4" fill="${colors[si]}" data-tip="${s.name}|${labels[i]}|${fmt(v)}" class="hoverable"/>`);});svg+=`</svg><div class="legend">${series.map((s,i)=>`<span><i style="background:${colors[i]}"></i>${s.name}</span>`).join("")}</div>`;el.innerHTML=svg;el.querySelectorAll(".hoverable").forEach(n=>{n.onmousemove=e=>{const a=n.dataset.tip.split("|");tooltipShow(e,`<b>${a[0]}</b><br>${a[1]} · ${a[2]} constituciones`)};n.onmouseleave=tooltipHide});}
function horizontalBars(container,items,valueKey,labelKey,color="#f28a3a"){const el=document.getElementById(container),max=Math.max(...items.map(x=>x[valueKey]));el.innerHTML=`<div style="display:grid;gap:12px">${items.map(x=>`<div><div style="display:flex;justify-content:space-between;gap:10px"><b>${x[labelKey]}</b><span class="subtle">${fmt(x[valueKey])}</span></div><div class="barline"><span style="width:${100*x[valueKey]/max}%;background:${color}"></span></div></div>`).join("")}</div>`;}
function renderKPIs(){const o=DATA.overview,growth=pct(o.ytd2026,o.ytd2025),spa=DATA.typesYTD[0].y2026*100/o.ytd2026,cards=[["Universo RES",fmt(o.total),"Sociedades únicas en la réplica"],["Constituciones 2026",fmt(o.ytd2026),`Ene–jul · <span class="${growth>=0?'pos':'neg'}">${growth>=0?'+':''}${growth.toFixed(1)}% vs 2025</span>`],["SpA 2026",spa.toFixed(1)+"%","Participación sobre constituciones YTD"],["Capital mediano",money(o.medianCapital),"Toda la base disponible"],["P90 capital",money(o.p90Capital),"Percentil 90 de la base"]];document.getElementById("kpis").innerHTML=cards.map(c=>`<div class="card kpi"><div class="label">${c[0]}</div><div class="value">${c[1]}</div><div class="delta">${c[2]}</div></div>`).join("");}
function renderTypeChart(){horizontalBars("typeChart",DATA.typesYTD.slice(0,4),"y2026","code")}
function renderWeekly(){svgLineChart("weeklyChart",DATA.weekly.map(x=>x[0].slice(5)),[{name:"Constituciones",values:DATA.weekly.map(x=>x[1])}],["#59c3c3"])}
function renderExecutive(){const growth=pct(DATA.overview.ytd2026,DATA.overview.ytd2025),fastest=DATA.regionSummary.filter(x=>x.r>0).map(x=>({...x,g:pct(x.y2026,x.y2025)})).sort((a,b)=>b.g-a.g)[0],topAn=DATA.anomalies[0],spaGrowth=pct(DATA.typesYTD[0].y2026,DATA.typesYTD[0].y2025);document.getElementById("executiveRead").innerHTML=`<div class="grid-3" style="grid-template-columns:1fr;gap:10px;margin:0"><div class="method"><strong>Volumen nacional</strong><p>2026 acumula <b>${fmt(DATA.overview.ytd2026)}</b> constituciones a julio, <span class="pos">+${growth.toFixed(1)}%</span> frente al mismo período 2025.</p></div><div class="method"><strong>Cambio de mix</strong><p>Las SpA suman <b>${fmt(DATA.typesYTD[0].y2026)}</b> constituciones YTD, <span class="pos">+${spaGrowth.toFixed(1)}%</span> interanual, mientras EIRL y SRL retroceden.</p></div><div class="method"><strong>Mayor aceleración regional YTD</strong><p><b>${REGIONS[fastest.r]}</b>: ${fmt(fastest.y2026)} sociedades, <span class="pos">+${fastest.g.toFixed(1)}%</span> vs ene–jul 2025.</p></div><div class="method"><strong>Desvío mensual destacado</strong><p><b>${REGIONS[topAn.r]} · ${MONTHS[topAn.m-1]}</b>: z=${topAn.z.toFixed(2)}, +${topAn.pct.toFixed(1)}% frente al promedio del mismo mes 2022–2025.</p></div></div>`;}
function renderCartogram(){const el=document.getElementById("cartogram"),order=[15,1,2,3,4,5,13,6,7,16,8,9,14,10,11,12],vals=DATA.regionSummary.filter(x=>x.r>0).map(x=>x.y2026),min=Math.min(...vals),max=Math.max(...vals),xs=[118,112,108,104,100,95,90,88,92,98,104,109,114,119,124,128];let svg=`<svg viewBox="0 0 300 540">`;order.forEach((r,i)=>{const d=DATA.regionSummary.find(x=>x.r===r),intensity=.18+.82*(Math.log(d.y2026)-Math.log(min))/(Math.log(max)-Math.log(min)),y=14+i*31,h=24,w=40+(i%3)*5,x=xs[i];svg+=`<rect class="region-seg ${r===selectedRegion?'active':''}" data-r="${r}" x="${x}" y="${y}" width="${w}" height="${h}" rx="10" fill="rgba(242,138,58,${intensity.toFixed(2)})"/>`;svg+=`<text class="region-label" x="${x+w+8}" y="${y+16}">${REGIONS[r]}</text>`;});svg+=`</svg>`;el.innerHTML=svg;el.querySelectorAll(".region-seg").forEach(n=>{n.onclick=()=>{selectedRegion=+n.dataset.r;document.getElementById("regionSelect").value=selectedRegion;document.getElementById("regionContext").textContent=REGIONS[selectedRegion];renderTerritory()};n.onmousemove=e=>{const r=+n.dataset.r,d=DATA.regionSummary.find(x=>x.r===r),g=pct(d.y2026,d.y2025);tooltipShow(e,`<b>${REGIONS[r]}</b><br>${fmt(d.y2026)} YTD · ${g>=0?'+':''}${g.toFixed(1)}% vs 2025`)};n.onmouseleave=tooltipHide;});}
function renderRegionDetail(){const sum=DATA.regionSummary.find(x=>x.r===selectedRegion),det=DATA.regionDetail.find(x=>x.r===selectedRegion);if(!sum||!det)return;const g=pct(sum.y2026,sum.y2025);document.getElementById("regionTitle").textContent=REGIONS[selectedRegion];document.getElementById("regionHeadline").innerHTML=`<div style="display:flex;gap:28px;align-items:flex-end;margin-bottom:10px"><div><div class="subtle">Constituciones YTD</div><div class="big-stat">${fmt(sum.y2026)}</div></div><div><div class="subtle">Variación</div><div style="font-size:22px;font-weight:800" class="${g>=0?'pos':'neg'}">${g>=0?'+':''}${g.toFixed(1)}%</div></div></div>`;svgLineChart("regionLine",MONTHS,[{name:"2026",values:det.y2026},{name:"2025",values:det.y2025}],["#f28a3a","#557188"]);const max=Math.max(...det.communes.map(x=>x[1]));document.getElementById("communes").innerHTML=det.communes.map(x=>`<div class="commune-row"><div><b>${x[0]}</b><div class="barline"><span style="width:${100*x[1]/max}%"></span></div></div><span>${fmt(x[1])}</span></div>`).join("");}
function renderRegionTable(){let rows=DATA.regionSummary.filter(x=>x.r>0).map(x=>({...x,g:pct(x.y2026,x.y2025)}));rows.sort((a,b)=>regionSort==="growth"?b.g-a.g:b.y2026-a.y2026);document.getElementById("regionTable").innerHTML=rows.map((x,i)=>`<tr data-r="${x.r}"><td><span class="rank">${i+1}</span></td><td><b>${REGIONS[x.r]}</b></td><td>${fmt(x.y2026)}</td><td>${fmt(x.y2025)}</td><td class="${x.g>=0?'pos':'neg'}">${x.g>=0?'+':''}${x.g.toFixed(1)}%</td><td>${money(x.median)}</td></tr>`).join("");document.querySelectorAll("#regionTable tr").forEach(tr=>tr.onclick=()=>{selectedRegion=+tr.dataset.r;document.getElementById("regionSelect").value=selectedRegion;document.getElementById("regionContext").textContent=REGIONS[selectedRegion];renderTerritory();window.scrollTo({top:210,behavior:"smooth"})});}
function renderTerritory(){renderCartogram();renderRegionDetail();renderRegionTable()}
function renderAnomalies(){const z=+document.getElementById("zRange").value;document.getElementById("zVal").textContent=z.toFixed(2);const rows=DATA.anomalies.filter(x=>x.z>=z&&(document.getElementById("regionSelect").value==="all"||+document.getElementById("regionSelect").value===x.r));document.getElementById("anomalyTable").innerHTML=rows.map(x=>`<tr><td><b>${REGIONS[x.r]}</b><br><span class="subtle">${MONTHS[x.m-1]} 2026</span></td><td>${fmt(x.n)}</td><td>${fmt(x.base)}</td><td class="pos">+${x.pct.toFixed(1)}%</td><td><span class="pill ${x.z>=4?'red':'orange'}">${x.z.toFixed(2)}</span></td></tr>`).join("")||`<tr><td colspan="5" class="subtle">Sin registros para este filtro.</td></tr>`;}
function currentClusters(){const min=+document.getElementById("clusterRange").value,q=document.getElementById("clusterSearch").value.toLowerCase().trim(),rv=document.getElementById("regionSelect").value;return DATA.clusters.filter(x=>x.n>=min).filter(x=>rv==="all"||x.r===+rv).filter(x=>!q||[x.commune,REGIONS[x.r],x.type,...x.names].join(" ").toLowerCase().includes(q));}
function renderClusters(){const min=+document.getElementById("clusterRange").value;document.getElementById("clusterVal").textContent=min;document.getElementById("clusterTable").innerHTML=currentClusters().map(x=>`<tr data-i="${DATA.clusters.indexOf(x)}"><td>${x.date}</td><td><b>${x.commune}</b><br><span class="subtle">${REGIONS[x.r]}</span></td><td><span class="pill">${x.type}</span></td><td>${money(x.capital)}</td><td><span class="pill orange">${x.n}</span></td></tr>`).join("")||`<tr><td colspan="5" class="subtle">Sin clusters para este filtro.</td></tr>`;document.querySelectorAll("#clusterTable tr[data-i]").forEach(tr=>tr.onclick=()=>openDrawer(DATA.clusters[+tr.dataset.i]));}
function openDrawer(x){document.getElementById("drawerTitle").textContent=`${x.commune} · ${x.n} sociedades`;document.getElementById("drawerMeta").innerHTML=`${x.date} · ${REGIONS[x.r]} · ${x.type} · capital ${money(x.capital)}`;document.getElementById("drawerNames").innerHTML=x.names.map(n=>`<div class="drawer-item">${n}</div>`).join("");document.getElementById("drawer").classList.add("open");}
function closeDrawer(){document.getElementById("drawer").classList.remove("open")}
function exportClusters(){const rows=currentClusters(),head=["fecha","region","comuna","tipo","capital","n","ejemplos"],csv=[head.join(";"),...rows.map(x=>[x.date,REGIONS[x.r],x.commune,x.type,x.capital,x.n,'"'+x.names.join(" | ").replaceAll('"','""')+'"'].join(";"))].join("\n"),blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="clusters_res_demo.csv";a.click();URL.revokeObjectURL(url);}
function renderCapital(){const arr=DATA.typesYTD.filter(x=>x.y2026>0).sort((a,b)=>b.median-a.median),max=Math.max(...arr.map(x=>x.median));document.getElementById("capitalType").innerHTML=arr.map(x=>`<div style="margin:12px 0"><div style="display:flex;justify-content:space-between"><b>${x.code}</b><span>${money(x.median)}</span></div><div class="barline"><span style="width:${100*x.median/max}%"></span></div></div>`).join("");}
function switchTab(id){document.querySelectorAll(".tabscreen").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".nav button").forEach(x=>x.classList.toggle("active",x.dataset.tab===id));if(id==="territorio")renderTerritory();if(id==="fenomenos"){renderAnomalies();renderClusters()}}
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
document.getElementById("sortVolume").onclick=()=>{regionSort="volume";renderRegionTable()};
document.getElementById("sortGrowth").onclick=()=>{regionSort="growth";renderRegionTable()};
document.getElementById("zRange").oninput=renderAnomalies;
document.getElementById("clusterRange").oninput=renderClusters;
document.getElementById("clusterSearch").oninput=renderClusters;
document.getElementById("exportClusters").onclick=exportClusters;
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDrawer()});
function initDemo(){try{if(!DATA)throw new Error("No se cargó data.js");buildRegionSelect();renderKPIs();svgBarChart("annualChart",DATA.annual);renderTypeChart();renderWeekly();renderExecutive();renderTerritory();renderAnomalies();renderClusters();renderCapital();const h=document.getElementById("healthBadge");if(h)h.textContent="Datos operativos ✓";}catch(err){console.error(err);const h=document.getElementById("healthBadge");if(h){h.textContent="Error de carga";h.style.color="#ffaaaa";h.style.borderColor="#663434";}const box=document.createElement("div");box.className="notice";box.style.margin="16px 0";box.innerHTML="<b>Error de inicialización de la demo.</b><br>"+String(err.message||err);document.querySelector("main").prepend(box);}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initDemo);else initDemo();
