(() => {
'use strict';
const DATA = window.RES_DATA;
if (!DATA) { document.body.innerHTML='<div style="padding:30px;color:white;background:#07111d">No se pudo cargar data.js</div>'; return; }
const REGIONS=DATA.regions, MONTHS=['Ene','Feb','Mar','Abr','May','Jun','Jul'];
const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat('es-CL').format(Math.round(Number(n)||0));
const money=n=>'$'+fmt(n);
const pct=(a,b)=>b?((a-b)*100/b):0;
const share=(n,d)=>d?100*n/d:0;
let activeTab=(location.hash||'#territorio').replace('#','');
if(!['pulso','territorio','fenomenos','estructura'].includes(activeTab)) activeTab='territorio';
let territoryRegion='all', territorySort='volume';
function tooltipShow(e,html){const t=$('tooltip');t.innerHTML=html;t.style.opacity=1;t.style.left=(e.clientX+10)+'px';t.style.top=(e.clientY+10)+'px';}
function tooltipHide(){const t=$('tooltip');t.style.opacity=0;}
function severity(score){return score>=80?['Crítica','critical']:score>=60?['Alta','high']:score>=40?['Media','medium']:['Baja','low'];}
function setScreen(id){activeTab=id;document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));history.replaceState(null,'','#'+id);if(id==='territorio')renderTerritory();if(id==='fenomenos')renderPhenomena();}
function regionOptions(select, includeAll=true){select.innerHTML=(includeAll?'<option value="all">Chile · todas</option>':'')+Object.entries(REGIONS).filter(([k])=>+k>0).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');}
function kpiCard(label,value,detail,tone=''){return `<div class="kpi card"><span>${label}</span><strong class="${tone}">${value}</strong><small>${detail}</small></div>`;}
function lineChart(container, labels, series){const el=$(container),W=760,H=225,p={l:28,r:10,t:14,b:32},iw=W-p.l-p.r,ih=H-p.t-p.b;const vals=series.flatMap(s=>s.values),max=Math.max(...vals)*1.12||1;const X=i=>p.l+iw*i/Math.max(1,labels.length-1),Y=v=>p.t+ih-v/max*ih;let svg=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">`;for(let i=0;i<4;i++){let y=p.t+ih*i/3;svg+=`<line class="gridline" x1="${p.l}" x2="${W-p.r}" y1="${y}" y2="${y}"/>`;}labels.forEach((l,i)=>svg+=`<text class="axis-label" x="${X(i)}" y="${H-10}" text-anchor="middle">${l}</text>`);const colors=['#f28a3a','#5f7d97','#59c3c3'];series.forEach((s,si)=>{svg+=`<polyline fill="none" stroke="${colors[si]}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" points="${s.values.map((v,i)=>`${X(i)},${Y(v)}`).join(' ')}"/>`;s.values.forEach((v,i)=>svg+=`<circle class="tip-node" data-tip="<b>${s.name}</b><br>${labels[i]} · ${fmt(v)}" cx="${X(i)}" cy="${Y(v)}" r="4" fill="${colors[si]}"/>`);});svg+='</svg><div class="legend">'+series.map((s,i)=>`<span><i style="background:${colors[i]}"></i>${s.name}</span>`).join('')+'</div>';el.innerHTML=svg;el.querySelectorAll('.tip-node').forEach(n=>{n.onmousemove=e=>tooltipShow(e,n.dataset.tip);n.onmouseleave=tooltipHide;});}
function barChart(container,pairs){const el=$(container),W=900,H=270,p={l:25,r:10,t:10,b:36},iw=W-p.l-p.r,ih=H-p.t-p.b,max=Math.max(...pairs.map(x=>x[1]))*1.08,bw=iw/pairs.length*.66,gap=iw/pairs.length;let s=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">`;pairs.forEach((d,i)=>{const h=ih*d[1]/max,x=p.l+i*gap+(gap-bw)/2,y=p.t+ih-h;s+=`<rect class="tip-node" data-tip="<b>${d[0]}</b><br>${fmt(d[1])} constituciones" x="${x}" y="${y}" width="${bw}" height="${h}" rx="5" fill="${d[0]===2026?'#f28a3a':'#36536c'}"/><text class="axis-label" x="${x+bw/2}" y="${H-12}" text-anchor="middle">${d[0]}</text>`;});s+='</svg>';el.innerHTML=s;el.querySelectorAll('.tip-node').forEach(n=>{n.onmousemove=e=>tooltipShow(e,n.dataset.tip);n.onmouseleave=tooltipHide;});}
function renderBars(el,items,maxVal,labelFn,valueFn){const mx=maxVal||Math.max(...items.map(valueFn),1);el.innerHTML=items.map(x=>`<div class="bar-item"><div><span>${labelFn(x)}</span><b>${fmt(valueFn(x))}</b></div><div class="bar-track"><i style="width:${Math.max(2,100*valueFn(x)/mx)}%"></i></div></div>`).join('')||'<div class="empty">Sin datos para el filtro.</div>';}
function renderPulso(){const o=DATA.overview,g=pct(o.ytd2026,o.ytd2025),spa=DATA.typesYTD[0];$('pulsoKpis').innerHTML=[kpiCard('Universo RES',fmt(o.total),'Sociedades únicas'),kpiCard('Constituciones 2026',fmt(o.ytd2026),`${g>=0?'+':''}${g.toFixed(1)}% vs 2025`,g>=0?'pos':'neg'),kpiCard('SpA 2026',(100*spa.y2026/o.ytd2026).toFixed(1)+'%',fmt(spa.y2026)+' sociedades'),kpiCard('Capital mediano',money(o.medianCapital),'Base disponible'),kpiCard('P90 capital',money(o.p90Capital),'Percentil 90')].join('');barChart('annualChart',DATA.annual);const top=DATA.typesYTD.filter(x=>x.y2026>0).slice(0,5);$('typeChart').innerHTML=top.map(x=>{const g=pct(x.y2026,x.y2025);return `<div class="type-row"><div><b>${x.code}</b><small>${fmt(x.y2026)} sociedades</small></div><div class="type-share"><span>${(100*x.y2026/o.ytd2026).toFixed(1)}%</span><small class="${g>=0?'pos':'neg'}">${g>=0?'+':''}${g.toFixed(1)}%</small></div></div>`;}).join('');lineChart('weeklyChart',DATA.weekly.map(x=>x[0].slice(5)),[{name:'Constituciones',values:DATA.weekly.map(x=>x[1])}]);const fastest=DATA.regionSummary.filter(x=>x.r>0).map(x=>({...x,g:pct(x.y2026,x.y2025)})).sort((a,b)=>b.g-a.g)[0],topAn=[...DATA.anomalies].sort((a,b)=>b.z-a.z)[0];$('executiveRead').innerHTML=`<div class="insight"><b>Volumen nacional</b><span>${fmt(o.ytd2026)} constituciones YTD, <em class="pos">+${g.toFixed(1)}%</em> interanual.</span></div><div class="insight"><b>Mix societario</b><span>SpA representa ${(100*spa.y2026/o.ytd2026).toFixed(1)}% de las constituciones 2026.</span></div><div class="insight"><b>Aceleración YTD</b><span>${REGIONS[fastest.r]} lidera crecimiento con <em class="pos">+${fastest.g.toFixed(1)}%</em>.</span></div><div class="insight"><b>Desvío mensual</b><span>${REGIONS[topAn.r]} · ${MONTHS[topAn.m-1]} alcanza z=${topAn.z.toFixed(2)}.</span></div>`;}
function selectedTerritory(){if(territoryRegion==='all')return null;return DATA.regionSummary.find(x=>x.r===+territoryRegion);}
function renderTerritoryKpis(){const national=DATA.overview.ytd2026;const s=selectedTerritory();if(!s){const fastest=DATA.regionSummary.filter(x=>x.r>0).map(x=>({...x,g:pct(x.y2026,x.y2025)})).sort((a,b)=>b.g-a.g)[0];const metro=DATA.regionSummary.find(x=>x.r===13);$('territoryKpis').innerHTML=[kpiCard('Chile YTD',fmt(national),'Enero–julio 2026'),kpiCard('Variación nacional','+'+pct(DATA.overview.ytd2026,DATA.overview.ytd2025).toFixed(1)+'%','vs mismo período 2025','pos'),kpiCard('Mayor aceleración',REGIONS[fastest.r],'+'+fastest.g.toFixed(1)+'% YTD','pos'),kpiCard('Mayor volumen',REGIONS[metro.r],fmt(metro.y2026)+' sociedades'),kpiCard('Regiones observadas','16','Cobertura territorial')].join('');}else{const d=DATA.regionDetail.find(x=>x.r===s.r),g=pct(s.y2026,s.y2025),topc=d?.communes?.[0];$('territoryKpis').innerHTML=[kpiCard('Constituciones YTD',fmt(s.y2026),REGIONS[s.r]),kpiCard('Variación',`${g>=0?'+':''}${g.toFixed(1)}%`,'vs ene–jul 2025',g>=0?'pos':'neg'),kpiCard('Cuota nacional',share(s.y2026,national).toFixed(1)+'%','Participación 2026'),kpiCard('Capital mediano',money(s.median),'Región seleccionada'),kpiCard('Comuna líder',topc?topc[0]:'—',topc?fmt(topc[1])+' constituciones':'Sin detalle')].join('');}}
function renderTerritoryMap(){const el=$('territoryMap'),order=[15,1,2,3,4,5,13,6,7,16,8,9,14,10,11,12],vals=DATA.regionSummary.filter(x=>x.r>0).map(x=>x.y2026),lo=Math.min(...vals),hi=Math.max(...vals);let svg='<svg viewBox="0 0 360 600" aria-label="Cartograma de Chile">';order.forEach((r,i)=>{const d=DATA.regionSummary.find(x=>x.r===r),t=(Math.log(d.y2026)-Math.log(lo))/(Math.log(hi)-Math.log(lo)),w=50+16*Math.sin(i/3),x=100+24*Math.sin(i/2.8),y=16+i*35,selected=territoryRegion!=='all'&&+territoryRegion===r;svg+=`<g class="map-region ${selected?'selected':''}" data-r="${r}"><rect x="${x}" y="${y}" width="${w}" height="27" rx="10" fill="rgba(242,138,58,${(.18+.8*t).toFixed(2)})"/><text x="${x+w+12}" y="${y+18}" class="map-label">${REGIONS[r]}</text></g>`;});svg+='</svg>';el.innerHTML=svg;el.querySelectorAll('.map-region').forEach(g=>{g.onclick=()=>{territoryRegion=g.dataset.r;$('territoryRegion').value=territoryRegion;renderTerritory();};g.onmousemove=e=>{const d=DATA.regionSummary.find(x=>x.r===+g.dataset.r);tooltipShow(e,`<b>${REGIONS[d.r]}</b><br>${fmt(d.y2026)} constituciones<br>${pct(d.y2026,d.y2025)>=0?'+':''}${pct(d.y2026,d.y2025).toFixed(1)}% vs 2025`)};g.onmouseleave=tooltipHide;});}
function renderTerritoryDetail(){const s=selectedTerritory();if(!s){$('territoryDetailTitle').textContent='Chile';$('territoryDetailSub').textContent='Evolución nacional reciente y lectura regional';$('territoryBadge').textContent='Nacional';$('territoryHeadline').innerHTML=`<div class="headline-grid"><div><span>Constituciones YTD</span><strong>${fmt(DATA.overview.ytd2026)}</strong></div><div><span>Variación</span><strong class="pos">+${pct(DATA.overview.ytd2026,DATA.overview.ytd2025).toFixed(1)}%</strong></div></div>`;lineChart('territoryLine',DATA.weekly.map(x=>x[0].slice(5)),[{name:'Chile · semanal',values:DATA.weekly.map(x=>x[1])}]);$('communeSub').textContent='Selecciona una región para ver sus principales comunas.';$('communeList').innerHTML='<div class="empty large">Selecciona una región en el cartograma o ranking para profundizar.</div>';return;}const d=DATA.regionDetail.find(x=>x.r===s.r),g=pct(s.y2026,s.y2025);$('territoryDetailTitle').textContent=REGIONS[s.r];$('territoryDetailSub').textContent='Enero–julio 2026 versus mismo período 2025';$('territoryBadge').textContent=g>=15?'Aceleración alta':g>=5?'Aceleración':'Estable';$('territoryBadge').className='severity '+(g>=15?'high':g>=5?'medium':'low');$('territoryHeadline').innerHTML=`<div class="headline-grid"><div><span>2026 YTD</span><strong>${fmt(s.y2026)}</strong></div><div><span>Variación</span><strong class="${g>=0?'pos':'neg'}">${g>=0?'+':''}${g.toFixed(1)}%</strong></div><div><span>Cuota nacional</span><strong>${share(s.y2026,DATA.overview.ytd2026).toFixed(1)}%</strong></div></div>`;if(d)lineChart('territoryLine',MONTHS,[{name:'2026',values:d.y2026},{name:'2025',values:d.y2025}]);$('communeSub').textContent='Constituciones enero–julio 2026.';if(d)renderBars($('communeList'),d.communes,null,x=>x[0],x=>x[1]);}
function renderTerritoryTable(){let rows=DATA.regionSummary.filter(x=>x.r>0).map(x=>({...x,g:pct(x.y2026,x.y2025),q:share(x.y2026,DATA.overview.ytd2026)}));rows.sort((a,b)=>territorySort==='growth'?b.g-a.g:b.y2026-a.y2026);$('territoryTable').innerHTML=rows.map((x,i)=>`<tr data-r="${x.r}" class="${territoryRegion!=='all'&&+territoryRegion===x.r?'selected-row':''}"><td><span class="rank">${i+1}</span></td><td><b>${REGIONS[x.r]}</b></td><td>${fmt(x.y2026)}</td><td>${fmt(x.y2025)}</td><td class="${x.g>=0?'pos':'neg'}">${x.g>=0?'+':''}${x.g.toFixed(1)}%</td><td>${x.q.toFixed(1)}%</td><td>${money(x.median)}</td></tr>`).join('');$('territoryTable').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>{territoryRegion=tr.dataset.r;$('territoryRegion').value=territoryRegion;renderTerritory();window.scrollTo({top:160,behavior:'smooth'});});}
function renderTerritoryWatch(){const rows=DATA.regionSummary.filter(x=>x.r>0).map(x=>({...x,g:pct(x.y2026,x.y2025)})).map(x=>({...x,score:Math.min(100,Math.round(Math.max(0,x.g)*2.1+Math.log10(x.y2026+1)*8))})).sort((a,b)=>b.score-a.score).slice(0,7);$('territoryWatch').innerHTML=rows.map((x,i)=>{const [lab,cls]=severity(x.score);return `<button class="watch-item" data-r="${x.r}"><span class="watch-rank">${i+1}</span><span><b>${REGIONS[x.r]}</b><small>${fmt(x.y2026)} sociedades · ${x.g>=0?'+':''}${x.g.toFixed(1)}%</small></span><span class="severity ${cls}">${lab}</span></button>`;}).join('');$('territoryWatch').querySelectorAll('button').forEach(b=>b.onclick=()=>{territoryRegion=b.dataset.r;$('territoryRegion').value=territoryRegion;renderTerritory();});}
function renderTerritory(){renderTerritoryKpis();renderTerritoryMap();renderTerritoryDetail();renderTerritoryTable();renderTerritoryWatch();}
function anomalyScore(x){return Math.min(100,Math.round(x.z*11+Math.max(0,x.pct)*.42));}
function clusterScore(x){const commonCapital=[1000000,5000000,10000000].includes(x.capital)?4:8;return Math.min(100,Math.round(x.n*2.45+commonCapital));}
function filteredAnomalies(){const z=+$('zRange').value,r=$('phenomenaRegion').value;return DATA.anomalies.filter(x=>x.z>=z&&(r==='all'||x.r===+r)).sort((a,b)=>anomalyScore(b)-anomalyScore(a));}
function filteredClusters(){const n=+$('clusterRange').value,r=$('phenomenaRegion').value,q=$('clusterSearch').value.trim().toLowerCase();return DATA.clusters.filter(x=>x.n>=n&&(r==='all'||x.r===+r)).filter(x=>!q||[x.commune,REGIONS[x.r],x.type,...x.names].join(' ').toLowerCase().includes(q)).sort((a,b)=>clusterScore(b)-clusterScore(a));}
function renderPhenomenaKpis(){const a=filteredAnomalies(),c=filteredClusters(),crit=a.filter(x=>x.z>=4).length,top=a[0],maxCluster=c[0];$('phenomenaKpis').innerHTML=[kpiCard('Anomalías visibles',fmt(a.length),`z ≥ ${(+$('zRange').value).toFixed(2)}`),kpiCard('Anomalías críticas',fmt(crit),'z ≥ 4',crit?'warn':''),kpiCard('Clusters visibles',fmt(c.length),`n ≥ ${$('clusterRange').value}`),kpiCard('Máximo desvío',top?top.z.toFixed(2):'—',top?`${REGIONS[top.r]} · ${MONTHS[top.m-1]}`:'Sin señales'),kpiCard('Mayor cluster',maxCluster?fmt(maxCluster.n):'—',maxCluster?`${maxCluster.commune} · ${maxCluster.date}`:'Sin señales')].join('');}
function renderAnomalies(){const rows=filteredAnomalies();$('anomalyCount').textContent=rows.length+' señales';const counts={};rows.forEach(x=>counts[x.r]=(counts[x.r]||0)+1);const byRegion=Object.entries(counts).map(([r,n])=>({r:+r,n})).sort((a,b)=>b.n-a.n).slice(0,7);renderBars($('anomalyBars'),byRegion,null,x=>REGIONS[x.r],x=>x.n);$('anomalyTable').innerHTML=rows.map(x=>{const sc=anomalyScore(x),[lab,cls]=severity(sc);return `<tr data-kind="anomaly" data-key="${x.r}-${x.m}"><td><b>${REGIONS[x.r]}</b><small>${MONTHS[x.m-1]} 2026</small></td><td>${fmt(x.n)}</td><td>${fmt(x.base)}</td><td class="pos">+${x.pct.toFixed(1)}%</td><td>${x.z.toFixed(2)}</td><td><span class="severity ${cls}">${lab}</span></td></tr>`;}).join('')||'<tr><td colspan="6" class="empty">Sin anomalías para estos filtros.</td></tr>';$('anomalyTable').querySelectorAll('tr[data-kind]').forEach(tr=>tr.onclick=()=>{const [r,m]=tr.dataset.key.split('-').map(Number);openAnomaly(DATA.anomalies.find(x=>x.r===r&&x.m===m));});}
function renderClusters(){const rows=filteredClusters();$('clusterTable').innerHTML=rows.map(x=>{const sc=clusterScore(x),[lab,cls]=severity(sc),idx=DATA.clusters.indexOf(x);return `<tr data-i="${idx}"><td>${x.date}</td><td><b>${x.commune}</b><small>${REGIONS[x.r]}</small></td><td>${x.type}</td><td>${money(x.capital)}</td><td><b>${x.n}</b></td><td><span class="severity ${cls}">${lab}</span></td></tr>`;}).join('')||'<tr><td colspan="6" class="empty">Sin clusters para estos filtros.</td></tr>';$('clusterTable').querySelectorAll('tr[data-i]').forEach(tr=>tr.onclick=()=>openCluster(DATA.clusters[+tr.dataset.i]));}
function renderQueue(){const a=filteredAnomalies().map(x=>({kind:'Aceleración',score:anomalyScore(x),title:`${REGIONS[x.r]} · ${MONTHS[x.m-1]} 2026`,meta:`z ${x.z.toFixed(2)} · +${x.pct.toFixed(1)}% vs base`,obj:x}));const c=filteredClusters().map(x=>({kind:'Cluster',score:clusterScore(x),title:`${x.commune} · ${x.date}`,meta:`${x.n} sociedades · ${x.type} · ${money(x.capital)}`,obj:x}));const q=[...a,...c].sort((x,y)=>y.score-x.score).slice(0,12);$('phenomenaQueue').innerHTML=q.map((x,i)=>{const [lab,cls]=severity(x.score);return `<button class="queue-card" data-kind="${x.kind}" data-index="${i}"><div><span class="queue-kind">${x.kind}</span><b>${x.title}</b><small>${x.meta}</small></div><div class="queue-score"><strong>${x.score}</strong><span class="severity ${cls}">${lab}</span></div></button>`;}).join('')||'<div class="empty large">Sin señales para los filtros actuales.</div>';$('phenomenaQueue').querySelectorAll('.queue-card').forEach((b,i)=>b.onclick=()=>{const item=q[i];item.kind==='Cluster'?openCluster(item.obj):openAnomaly(item.obj);});}
function renderPhenomena(){ $('zVal').textContent=(+$('zRange').value).toFixed(2);$('clusterVal').textContent=$('clusterRange').value;renderPhenomenaKpis();renderAnomalies();renderClusters();renderQueue();}
function openDrawer(kind,title,meta,body){$('drawerKind').textContent=kind;$('drawerTitle').textContent=title;$('drawerMeta').innerHTML=meta;$('drawerBody').innerHTML=body;$('drawer').classList.add('open');}
function openCluster(x){const sc=clusterScore(x),[lab,cls]=severity(sc);openDrawer('CLUSTER CONSTITUTIVO',`${x.commune} · ${x.n} sociedades`,`${x.date} · ${REGIONS[x.r]} · ${x.type} · capital ${money(x.capital)} · <span class="severity ${cls}">${lab}</span>`,`<div class="drawer-section"><h4>Coincidencia observada</h4><p>Misma fecha de constitución, comuna, tipo societario y capital informado.</p></div><div class="drawer-section"><h4>Ejemplos de sociedades</h4>${x.names.map(n=>`<div class="entity-chip">${n}</div>`).join('')}</div><div class="notice"><b>Alcance:</b> esta coincidencia no demuestra representante, domicilio exacto ni vínculo común.</div>`);}
function openAnomaly(x){const sc=anomalyScore(x),[lab,cls]=severity(sc);openDrawer('ACELERACIÓN TERRITORIAL',`${REGIONS[x.r]} · ${MONTHS[x.m-1]} 2026`,`Actual ${fmt(x.n)} · base ${fmt(x.base)} · +${x.pct.toFixed(1)}% · z=${x.z.toFixed(2)} · <span class="severity ${cls}">${lab}</span>`,`<div class="drawer-section"><h4>Qué significa</h4><p>El volumen del mes se aparta del comportamiento observado para ese mismo mes entre 2022 y 2025.</p></div><div class="metric-pair"><div><span>Actual</span><b>${fmt(x.n)}</b></div><div><span>Base comparable</span><b>${fmt(x.base)}</b></div></div><div class="notice"><b>Uso:</b> prioriza revisión territorial. No constituye una alerta AML.</div>`);}
function exportClusters(){const rows=filteredClusters(),head=['fecha','region','comuna','tipo','capital','n','prioridad','ejemplos'];const csv=[head.join(';'),...rows.map(x=>[x.date,REGIONS[x.r],x.commune,x.type,x.capital,x.n,clusterScore(x),'"'+x.names.join(' | ').replaceAll('"','""')+'"'].join(';'))].join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='res_clusters_filtrados.csv';a.click();URL.revokeObjectURL(url);}
function renderCapital(){const arr=DATA.typesYTD.filter(x=>x.y2026>0).sort((a,b)=>b.median-a.median);renderBars($('capitalType'),arr,null,x=>x.code,x=>x.median);$('capitalType').querySelectorAll('.bar-item b').forEach((b,i)=>b.textContent=money(arr[i].median));}
function init(){regionOptions($('territoryRegion'));regionOptions($('phenomenaRegion'));$('territoryRegion').value='all';$('phenomenaRegion').value='all';document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>setScreen(b.dataset.tab));$('territoryRegion').onchange=e=>{territoryRegion=e.target.value;renderTerritory();};$('territoryReset').onclick=()=>{territoryRegion='all';$('territoryRegion').value='all';renderTerritory();};document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{territorySort=b.dataset.sort;document.querySelectorAll('.segmented button').forEach(x=>x.classList.toggle('active',x===b));renderTerritoryTable();});['zRange','clusterRange'].forEach(id=>$(id).oninput=renderPhenomena);$('phenomenaRegion').onchange=renderPhenomena;$('clusterSearch').oninput=renderPhenomena;$('phenomenaReset').onclick=()=>{$('phenomenaRegion').value='all';$('zRange').value=3;$('clusterRange').value=15;$('clusterSearch').value='';renderPhenomena();};$('exportClusters').onclick=exportClusters;$('drawerClose').onclick=()=> $('drawer').classList.remove('open');document.addEventListener('keydown',e=>{if(e.key==='Escape')$('drawer').classList.remove('open');});renderPulso();renderTerritory();renderPhenomena();renderCapital();setScreen(activeTab);$('healthBadge').textContent='Datos operativos ✓';}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();