(() => {
'use strict';
const DATA=window.RES_DATA, INS=window.RES_INSIGHTS, BASE=window.RES_ENTITIES||[], EXTRA=window.RES_SUPPORT_ENTITIES||[], SUPPORT=window.RES_SUPPORT||{criticalDates:[],nameFamilies:[]};
if(!DATA||!INS)return;
const REG=DATA.regions;
const byRut=new Map();[...BASE,...EXTRA].forEach(e=>byRut.set(e.rut,e));const ENT=[...byRut.values()];
const fmt=n=>new Intl.NumberFormat('es-CL').format(Math.round(Number(n)||0));
const money=n=>'$'+fmt(n), esc=s=>String(s??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const fmtDate=s=>{if(!s)return'—';const [y,m,d]=s.split('-');return`${d}/${m}/${y}`};
const standardCaps=new Set([100000,200000,300000,500000,1000000,1500000,2000000,3000000,4000000,5000000,6000000,7000000,8000000,10000000,15000000,20000000,30000000]);
const PHEN_COHORTS={'metro-pattern':['PROVIDENCIA_SPA_1M','LAS_CONDES_SPA_1M','SANTIAGO_SPA_1M'],'arica':['ARICA'],'macul':['MACUL_SPA_5M'],'huechuraba':['HUECHURABA','SIM_KAMI'],'victoria':['VICTORIA']};
let activeFilter={kind:'all',value:null,label:'Todas las sociedades navegables',context:'Muestra navegable de la demo; Atlas consultará el universo completo.'};
let sortKey='constitution_date',sortDir='desc';
function typeMedian(code){const x=DATA.typesYTD.find(t=>t.code===code);return x?Number(x.median):Number(DATA.overview.medianCapital);}
function cohortBand(n){return n>=10?['Cohorte alta','high']:n>=3?['Cohorte media','medium']:['Cohorte baja','low'];}
function lexicalTokens(name){const n=norm(name);return INS.vocabulary.filter(v=>n.includes(norm(v.token))).map(v=>v.token).slice(0,6);}
function field(label,value,meta=''){return`<div class="entity-field"><span>${esc(label)}</span><b>${esc(value)}</b><small>${esc(meta)}</small></div>`;}
function openEntity(e){
 const median=typeMedian(e.company_code),ratio=median?Number(e.capital)/median:0,territorySame=e.social_commune===e.tax_commune&&Number(e.social_region)===Number(e.tax_region),cohort=cohortBand(Number(e.cohort_size)),tokens=lexicalTokens(e.legal_name),isStd=standardCaps.has(Number(e.capital));
 const body=document.getElementById('entityDrawerBody');if(!body)return;
 body.innerHTML=`<div class="entity-title"><div><h2>${esc(e.legal_name)}</h2><p>${esc(e.rut)} · ${esc(e.company_code)}</p></div><span class="entity-cohort ${cohort[1]}">${cohort[0]}</span></div>
 <div class="entity-chips"><span class="entity-chip">${esc(e.company_code)}</span><span class="entity-chip">Capital ${isStd?'estándar':'no estándar'}</span><span class="entity-chip">${cohort[0]}</span><span class="entity-chip">${e.lag_sii_days===0?'SII mismo día':`SII +${e.lag_sii_days}d`}</span><span class="entity-chip">${territorySame?'Territorio coincidente':'Territorio difiere'}</span></div>
 <div class="entity-kpis"><div><span>Capital</span><b>${money(e.capital)}</b><small>${ratio.toFixed(1)}× mediana ${esc(e.company_code)}</small></div><div><span>Constitución</span><b>${fmtDate(e.constitution_date)}</b><small>${esc(e.social_commune)}</small></div><div><span>Cohorte exacta</span><b>${fmt(e.cohort_size)}</b><small>mismo día + comuna + tipo + capital</small></div><div><span>Rezago SII</span><b>${e.lag_sii_days} d</b><small>desde constitución</small></div></div>
 <section class="entity-section"><h3>Identificación</h3><div class="field-grid">${field('RUT',e.rut,'Dato RES')}${field('Razón social',e.legal_name,'Dato RES')}${field('Tipo societario',e.company_code,'Dato RES')}${field('Capital declarado',money(e.capital),'Dato RES')}</div></section>
 <section class="entity-section"><h3>Cronología registral</h3><div class="timeline-mini"><div><i></i><b>Constitución</b><span>${fmtDate(e.constitution_date)}</span><small>día 0</small></div><div><i></i><b>Registro</b><span>${fmtDate(e.registry_date)}</span><small>+${e.lag_registry_days} días</small></div><div><i></i><b>Aprobación SII</b><span>${fmtDate(e.sii_approval_date)}</span><small>+${e.lag_sii_days} días</small></div></div></section>
 <section class="entity-section"><h3>Territorio</h3><div class="field-grid">${field('Comuna social',e.social_commune,REG[e.social_region])}${field('Comuna tributaria',e.tax_commune,REG[e.tax_region])}${field('Consistencia territorial',territorySame?'Coincidente':'Diferente','Comparación social vs tributaria')}</div></section>
 <section class="entity-section"><h3>Caracterización de capital</h3><div class="field-grid">${field('Capital declarado',money(e.capital),'Dato RES')}${field('Mediana del tipo',money(median),`Mediana YTD ${esc(e.company_code)}`)}${field('Relación vs mediana',ratio.toFixed(2)+'×','Caracterización derivada')}${field('Capital estandarizado',isStd?'Sí':'No','Catálogo de montos recurrentes')}</div></section>
 <section class="entity-section"><h3>Contexto de cohorte</h3><div class="cohort-box"><strong>${fmt(e.cohort_size)} sociedades</strong><span>comparten exactamente <b>${fmtDate(e.constitution_date)} + ${esc(e.social_commune)} + ${esc(e.company_code)} + ${money(e.capital)}</b>.</span><small>Caracteriza simultaneidad estructural; no implica vínculo entre sociedades.</small></div></section>
 <section class="entity-section"><h3>Razón social</h3>${tokens.length?`<div class="token-row">${tokens.map(t=>`<span>${esc(t)}</span>`).join('')}</div><p class="muted">Coincidencias con vocabulario emergente de la ventana reciente.</p>`:'<p class="muted">Sin coincidencias con el vocabulario emergente seleccionado.</p>'}</section>
 <section class="entity-section provenance"><h3>Proveniencia</h3><p><b>Fuente:</b> Registro de Empresas y Sociedades · réplica <code>aml_res_company</code> · corte 31/07/2026.</p><p>No contiene socios, representantes, administradores, personas naturales ni inferencias de actividad económica.</p></section>`;
 document.getElementById('entityDrawer').classList.add('open');
}
function filteredEntities(){
 let rows=ENT;
 if(activeFilter.kind==='cohorts')rows=rows.filter(e=>activeFilter.value.includes(e.cohort));
 else if(activeFilter.kind==='commune')rows=rows.filter(e=>e.social_commune===activeFilter.value);
 else if(activeFilter.kind==='date')rows=rows.filter(e=>e.constitution_date===activeFilter.value);
 else if(activeFilter.kind==='ruts'){const s=new Set(activeFilter.value);rows=rows.filter(e=>s.has(e.rut));}
 else if(activeFilter.kind==='search'){const q=norm(activeFilter.value);rows=rows.filter(e=>norm(e.legal_name).includes(q)||norm(e.rut).includes(q));}
 return rows.slice().sort((a,b)=>{let av=a[sortKey],bv=b[sortKey];if(sortKey==='capital'||sortKey==='cohort_size'){av=Number(av);bv=Number(bv);}else{av=String(av||'');bv=String(bv||'');}return (av<bv?-1:av>bv?1:0)*(sortDir==='asc'?1:-1);});
}
function characterize(e){const med=typeMedian(e.company_code),ratio=med?Number(e.capital)/med:0;const bits=[];if(e.cohort_size>=10)bits.push('cohorte alta');else if(e.cohort_size>=3)bits.push('cohorte media');if(standardCaps.has(Number(e.capital)))bits.push('capital recurrente');if(ratio>=5)bits.push('capital alto vs tipo');if(e.lag_sii_days>1)bits.push(`SII +${e.lag_sii_days}d`);return bits.length?bits.join(' · '):'sin rasgo destacado';}
function renderTable(scroll=false){
 const body=document.getElementById('entityExplorer'),label=document.getElementById('entityFilterLabel'),count=document.getElementById('entityTableCount'),ctx=document.getElementById('entityTableContext');if(!body)return;
 const rows=filteredEntities();if(label)label.textContent=activeFilter.label;if(count)count.textContent=fmt(rows.length);if(ctx)ctx.textContent=activeFilter.context;
 body.innerHTML=rows.length?rows.map(e=>`<tr data-rut="${esc(e.rut)}"><td><b>${esc(e.rut)}</b></td><td><b>${esc(e.legal_name)}</b></td><td><span class="entity-type">${esc(e.company_code)}</span></td><td>${fmtDate(e.constitution_date)}</td><td><b>${esc(e.social_commune)}</b><small>${esc(REG[e.social_region])}</small></td><td>${money(e.capital)}</td><td><span class="cohort-count ${e.cohort_size>=10?'high':e.cohort_size>=3?'medium':''}">${fmt(e.cohort_size)}</span></td><td><small>${esc(characterize(e))}</small></td></tr>`).join(''):`<tr><td colspan="8"><div class="empty table-empty">La muestra demo no contiene entidades para esta selección. En Atlas el filtro consultará el universo completo de <code>aml_res_company</code>.</div></td></tr>`;
 body.querySelectorAll('tr[data-rut]').forEach(tr=>tr.onclick=()=>openEntity(byRut.get(tr.dataset.rut)));
 document.querySelectorAll('.phen-dot').forEach(n=>n.classList.toggle('selected-filter',activeFilter.kind==='cohorts'&&(PHEN_COHORTS[n.dataset.id]||[]).some(c=>activeFilter.value.includes(c))));
 if(scroll){const card=body.closest('.entity-explorer-card');if(card)card.scrollIntoView({behavior:'smooth',block:'start'});}
}
function setFilter(f,scroll=true){activeFilter=f;renderTable(scroll);}
function initSearch(){const input=document.getElementById('entitySearch'),box=document.getElementById('entitySearchResults');if(!input||!box)return;input.oninput=()=>{const q=norm(input.value.trim());if(q.length<2){box.classList.remove('open');box.innerHTML='';return;}const rows=ENT.filter(e=>norm(e.legal_name).includes(q)||norm(e.rut).includes(q)).slice(0,10);box.innerHTML=rows.length?rows.map(e=>`<button data-rut="${e.rut}"><b>${esc(e.legal_name)}</b><span>${esc(e.rut)} · ${esc(e.social_commune)} · ${money(e.capital)}</span></button>`).join(''):`<div class="search-empty"><b>Sin coincidencia en la muestra.</b><span>Atlas consultará el universo completo.</span></div>`;box.classList.add('open');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{box.classList.remove('open');input.value='';openEntity(byRut.get(b.dataset.rut));});};document.addEventListener('click',e=>{if(!e.target.closest('.entity-search-shell'))box.classList.remove('open');});}
function scoreComm(c){const pct=(a,b)=>b?100*(a-b)/b:0;const m=pct(c.last30,c.prev30),y=pct(c.last30,c.yoy30);return Math.max(0,m)*.45+Math.max(0,y)*.45+Math.log10(c.last30+1)*8;}
function renderCriticalDates(){const el=document.getElementById('criticalDates');if(!el)return;el.innerHTML=SUPPORT.criticalDates.map(d=>`<button class="support-row ${d.state}" data-date="${d.date}"><span><b>${fmtDate(d.date)}</b><small>${d.holiday?`Feriado · ${esc(d.holiday)}`:'Baseline comparable por calendario'}</small></span><span class="support-metric"><strong>${fmt(d.count)}</strong><small>base ${fmt(d.baseline)} · z ${Number(d.z).toFixed(2)}</small></span><em>${d.state==='high'?'Pico':'Caída'}</em></button>`).join('');el.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{const d=SUPPORT.criticalDates.find(x=>x.date===b.dataset.date);setFilter({kind:'date',value:d.date,label:`Fecha crítica · ${fmtDate(d.date)}`,context:`${d.state==='high'?'Pico':'Caída'} de constituciones: ${fmt(d.count)} vs baseline ${fmt(d.baseline)} (z ${d.z}). ${d.holiday?'La fecha coincide con feriado; interpretar con cautela.':'Baseline ajustado por mes y día de semana.'}`});});}
function renderCriticalCommunes(){const el=document.getElementById('criticalCommunes');if(!el)return;const pct=(a,b)=>b?100*(a-b)/b:0,present=new Set(ENT.map(e=>e.social_commune)),rows=INS.communeSignals.filter(c=>present.has(c.commune)).slice().sort((a,b)=>scoreComm(b)-scoreComm(a)).slice(0,8);el.innerHTML=rows.map(c=>{const m=pct(c.last30,c.prev30),y=pct(c.last30,c.yoy30);return`<button class="support-row commune" data-commune="${esc(c.commune)}"><span><b>${esc(c.commune)}</b><small>${esc(REG[c.r])} · ${fmt(c.last30)} en 30d</small></span><span class="support-metric"><strong>${m>=0?'+':''}${m.toFixed(1)}%</strong><small>a/a ${y>=0?'+':''}${y.toFixed(1)}%</small></span><em>${c.spa.toFixed(0)}% SpA</em></button>`}).join('');el.querySelectorAll('[data-commune]').forEach(b=>b.onclick=()=>setFilter({kind:'commune',value:b.dataset.commune,label:`Comuna · ${b.dataset.commune}`,context:'Sociedades navegables de la comuna seleccionada. El filtro se origina en la señal territorial reciente.'}));}
function renderSimilarNames(){const el=document.getElementById('similarNames');if(!el)return;el.innerHTML=SUPPORT.nameFamilies.map(f=>`<button class="support-row names" data-family="${f.id}"><span><b>${esc(f.label)}</b><small>${fmtDate(f.date)} · ${esc(f.commune)} · ${esc(f.type)} · ${money(f.capital)}</small></span><span class="support-metric"><strong>${f.count}</strong><small>${f.kind==='exact'?'RUT distintos, misma denominación':'denominaciones de una serie léxica'}</small></span><em>${f.kind==='exact'?'Idénticas':'Parecidas'}</em></button>`).join('');el.querySelectorAll('[data-family]').forEach(b=>{b.onclick=()=>{const f=SUPPORT.nameFamilies.find(x=>x.id===b.dataset.family);setFilter({kind:'ruts',value:f.ruts,label:`Razón social · ${f.label}`,context:`${f.count} sociedades observadas en ${f.commune} el ${fmtDate(f.date)} con patrón ${f.kind==='exact'?'de denominación idéntica':'léxico serial'}. No implica vínculo societario.`});};});}
function installBubbleFilter(){document.addEventListener('click',ev=>{const dot=ev.target.closest&&ev.target.closest('.phen-dot[data-id]');if(!dot)return;ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();const id=dot.dataset.id,cs=PHEN_COHORTS[id]||[];if(cs.length)setFilter({kind:'cohorts',value:cs,label:`Fenómeno · ${id}`,context:'Nómina filtrada desde la burbuja seleccionada. La ficha individual conserva datos RES y contexto de cohorte.'});else setFilter({kind:'all',value:null,label:`Fenómeno ${id} · sin muestra individual`,context:'La señal existe en la analítica agregada, pero esta demo no contiene entidades individuales suficientes para ese fenómeno.'});},true);}
function installAnalyticDrilldowns(){document.addEventListener('click',ev=>{const phen=ev.target.closest&&ev.target.closest('.phenomenon-card[data-id]');if(phen){const cs=PHEN_COHORTS[phen.dataset.id]||[];if(cs.length)setTimeout(()=>setFilter({kind:'cohorts',value:cs,label:`Fenómeno · ${phen.dataset.id}`,context:'Filtro sincronizado con el fenómeno abierto.'},false),0);return;}const accel=ev.target.closest&&ev.target.closest('#accelTable tr[data-c]');if(accel)setTimeout(()=>setFilter({kind:'commune',value:accel.dataset.c,label:`Comuna · ${accel.dataset.c}`,context:'Filtro sincronizado con aceleración comunal.'},false),0);const rec=ev.target.closest&&ev.target.closest('#recurrentTable tr[data-i]');if(rec){const x=INS.recurrentClusters[+rec.dataset.i];setTimeout(()=>{const ruts=ENT.filter(z=>z.social_commune===x.commune&&z.company_code===x.type&&Number(z.capital)===Number(x.capital)).map(z=>z.rut);setFilter({kind:'ruts',value:ruts,label:`Recurrencia · ${x.commune} · ${x.type} · ${money(x.capital)}`,context:'Sociedades de la muestra que coinciden con la configuración recurrente seleccionada.'},false)},0);}},true);}
function initSort(){document.querySelectorAll('.entity-table th').forEach((th,i)=>{const keys=['rut','legal_name','company_code','constitution_date','social_commune','capital','cohort_size',null];if(!keys[i])return;th.classList.add('sortable');th.onclick=()=>{const k=keys[i];if(sortKey===k)sortDir=sortDir==='asc'?'desc':'asc';else{sortKey=k;sortDir=k==='legal_name'||k==='rut'||k==='social_commune'?'asc':'desc';}renderTable(false);};});}
function init(){const count=document.getElementById('entitySampleCount');if(count)count.textContent=ENT.length;initSearch();renderCriticalDates();renderCriticalCommunes();renderSimilarNames();renderTable(false);installBubbleFilter();installAnalyticDrilldowns();initSort();const clear=document.getElementById('entityClearFilter');if(clear)clear.onclick=()=>setFilter({kind:'all',value:null,label:'Todas las sociedades navegables',context:'Muestra navegable de la demo; Atlas consultará el universo completo.'});const close=document.getElementById('entityDrawerClose');if(close)close.onclick=()=>document.getElementById('entityDrawer').classList.remove('open');document.addEventListener('keydown',e=>{if(e.key==='Escape')document.getElementById('entityDrawer').classList.remove('open');});const badge=document.getElementById('healthBadge');if(badge)badge.textContent='Datos + filtros + fichas ✓';}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
